export const LOGINOUT='LOGINOUT';
export const ADDVALUE='ADDVALUE';
export const ADDGOODS = 'ADDGOODS';
export const INIT='INIT';
export const GETPAGE = 'GETPAGE';
export const SETPAGE ='SETPAGE';
export const GETTOTAL ='GETTOTAL';
export const TOGGLE='TOGGLE';
export const CHECKEDALL='CHECKEDALL';
export const PROAUDIT='PROAUDIT';
export const AUDITCANCEL ='AUDITCANCEL';
export const AUDITENSURE ='AUDITENSURE';
export const AUDITLIST ='AUDITLIST';
export const AUDITDETAILCANCEL ='AUDITDETAILCANCEL';
export const TIMEFORMAT ='TIMEFORMAT'
export const PRODUCTEDIT ='PRODUCTEDIT';
export const SUBMITEDITINFO ='SUBMITEDITINFO';
export const PRODUCTDELETE ='PRODUCTDELETE';
export const PRODUCTRESTORE ='PRODUCTRESTORE';
export const PROREMOVESHOW ='PROREMOVESHOW';
export const REMOVECANCEL ='REMOVECANCEL'
export const REMOVEENSURE = 'REMOVEENSURE';
export const MASSAUDIT ='MASSAUDIT';
export const BRANDLIST='BRANDLIST';
export const SEARCHBRAND ='SEARCHBRAND';
export const SEARCHCONTENT ='SEARCHCONTENT';
export const PRODUCTSEARCH ='PRODUCTSEARCH';
export const CHANGESEARCHONOFF ='CHANGESEARCHONOFF';
export const CHANGESORT ='CHANGESORT';
export const PRODUCTDATA ='PRODUCTDATA';
//订单
export const PROORDERGET ='PROORDERGET';
export const ORDERLISTINIT ='ORDERLISTINIT';
export const ORDERTOGGLE ='ORDERTOGGLE';
export const ORDEROPERATION ='ORDEROPERATION';
export const ORDERGETPAGE ='ORDERGETPAGE';
export const ORDERALL ='ORDERALL';
export const ORDERGETTOTAL ='ORDERGETTOTAL';
export const ORDERDATA ='ORDERDATA';

//待处理事项
export const GETPENDING ='GETPENDING';


//获取每天的订单数据
export const EVERYDAYDATA ='EVERYDAYDATA';